version: "3.3"

services:
  # tg-user:
  #   build: ../
  #   ports:
  #     - "8005:8005"
  #   depends_on:
  #     - tg-user-rethinkdb
  #   networks:
  #     - restserve_ecosystem
  #   environment:
  #     - DB_HOST=tg-user-rethinkdb

  tg-user-rethinkdb: 
    image: rethinkdb
    networks: 
      - restserve_ecosystem
    ports: 
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
       
networks: 
  restserve_ecosystem: 
    driver: bridge