version: "3"

services:

  rethinkdb: 
    image: rethinkdb
    networks: 
      - restserve_ecosystem
    ports: 
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    
networks: 
  restserve_ecosystem: 
    driver: bridge